---
abstract: 'A SQL Query library'
author:
  - 'Matias Alejo Garcia ( matiu@cpan.org ) '
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Bibliosoph
no_index:
  directory:
    - t
    - inc
requires:
  Cache::Memcached::Fast: 0.17
  Carp: 1.25
  DBD::Mock: 1.43
  DBD::mysql: 4.004
  DBI: 1.5
  Digest::MD5: 2.39
  Exception::Class: 1.3
  Log::Contextual: 0.005003
  Moose: 0.82
  Package::Constants: 0.02
  Storable: 2.3
  Test::More: 0.88
  Tie::Array::Random: 1
  Tie::Hash::Random: 1
  Time::HiRes: 1.97
  perl: 5.010000
version: 2.54
