--- #YAML:1.0
name:               SQL-Bibliosoph
version:            2.00
abstract:           A SQL Query library
author:
    - Matias Alejo Garcia ( matiu@cpan.org ) 
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                ~
    DBD::Mock:           ~
    DBD::mysql:          4.004
    DBI:                 1.5
    Moose:               0.82
    Package::Constants:  ~
    Test::More:          0.88
    Tie::Array::Random:  1
    Tie::Hash::Random:   1
    Time::HiRes:         ~
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
